<!DOCTYPE html>
<html>
<head>
    <!--For mobiles -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <!-- Reset.css -->
    <link rel="stylesheet" type="text/css" href="css/eric-meyer-reset.min.css">

    <!-- Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Vollkorn:700,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather+Sans:400,300,300italic' rel='stylesheet' type='text/css'>
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!-- Jquery -->
    <script type="text/javascript" src="js/jquery-1.9.1.min.js"></script>

    <!-- Materialize theme-->
        <!-- Compiled and minified CSS -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.1/css/materialize.min.css">
        <!-- Compiled and minified JavaScript -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.1/js/materialize.min.js"></script>

    <!-- Custom JS -->
    <script type="text/javascript" src="js/main.js"></script>

    <!-- Custom styles-->
    <link rel="stylesheet" type="text/css" href="css/index.css">

    <title>LovelySurvey: free online survey software</title>
</head>
<body>
    <nav class="red lighten-1" role="navigation">
        <div class="nav-wrapper container"><a id="logo-container" href="#" class="brand-logo">LovelySurvey</a>

          <ul class="right hide-on-med-and-down">
            <li><a href="#">Home</a></li>
            <li><a href="#">Get started</a></li>
            <li><a href="#">Servises</a></li>
            <li><a href="#">Plans & pricing</a></li>
            <li><a href="#">Contacts</a></li>
          </ul>

          <ul id="nav-mobile" class="side-nav">
            <li><a href="#">Home</a></li>
            <li><a href="#">Get started</a></li>
            <li><a href="#">Servises</a></li>
            <li><a href="#">Plans & pricing</a></li>
            <li><a href="#">Contacts</a></li>
          </ul>
          <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
        </div>
    </nav>
    <div class="section no-pad-bot grey lighten-4" id="index-banner">
        <div class="container">
          <br><br>
          <h1 class="header center grey-text">Make your survey with <span class="red-text">LOVE</span>ly survey</h1>
          <div class="row center">
            <h5 class="header col s12 light">Create Surveys, Get Answers, Be professional</h5>
          </div>
          <div class="row center">
            <br>
            <a href="#" id="get-started-button" class="btn-large waves-effect red waves-light">Get Started</a>
          </div>
        </div>
    </div>

    <div class="container introduction" >
        <div class="section">
          <div class="row">
            <h4 class="col s12">Introducing Lovely Survey</h4>

            <div class="col s2">
              <img src="img/real-time.png">
            </div>
            <div class="col s4">
              <article>
                <h5>Watch each question appear in real time as you create it.</h5>
                Choose from wide range of question types, including multiple choice, form, essay, scoring, and scale. You can have as many questions as you want in a survey!
              </article>
            </div>

            <div class="col s2">
              <img src="img/themes.png">
            </div>
            <div class="col s4">
              <article>
                <h5>Themes can make your surveys look even better.</h5>
                SurveyPlanet surveys already look fantastic, and when you add themes to them, they’ll look fantastically unique. Free SurveyPlanet users can choose between ten colorful survey themes. Our Pro users can build custom themes using over fifty color palettes, twenty-five different fonts, and forty-five background textures.
              </article>
            </div>
          </div>

          <div class="row">
            <div class="col s2">
              <img src="img/review.png">
            </div>
            <div class="col s4">
              <article>
                <h5>Preview Mode lets you review your surveys with ease.</h5>
                We’ve made it as simple as possible to review your surveys before sharing them. Click on the Preview icon and your survey will open in a new tab, allowing you to see question and its choices from the perspective of your survey takers.
              </article>
            </div>

            <div class="col s2">
              <img src="img/images.png">
            </div>
            <div class="col s4">
              <article>
                <h5>SurveyPlanet Pro surveys are pretty as a picture.</h5>
                SurveyPlanet Pro users know that a picture really can be worth a thousand words – or more! Pro users have access to our Image Choice question type. They can also add images to their survey questions and to their survey opening and closing messages.
              </article>
            </div>
          </div>
        </div>
    </div>

    <!--   Icon Section   -->
    <div class="grey lighten-4">
      <div class="container">
        <div class="section">
          <div class="row">
            <div class="col s12 m3">
              <div class="icon-block">
                <h2 class="center indigo-text text-lighten-4"><i class="material-icons large">supervisor_account</i></h2>
                <h5 class="center grey-text text-darken-2">Survey your target market</h5>
              </div>
            </div>

            <div class="col m1 hide-on-small-and-down">
              <div class="arrow-between-main-icons">
                <h2 class="center grey-text text-lighten-2"><i class="material-icons medium">keyboard_arrow_right</i></h2>
              </div>
            </div>

            <div class="col s12 m4">
              <div class="icon-block">
                <h2 class="center indigo-text text-lighten-4"><i class="material-icons large">question_answer</i></h2>
                <h5 class="center grey-text text-darken-2">Learn what your customers want</h5>
              </div>
            </div>

            <div class="col m1 hide-on-small-and-down">
              <div class="arrow-between-main-icons">
                <h2 class="center grey-text text-lighten-2"><i class="material-icons medium">keyboard_arrow_right</i></h2>
              </div>
            </div>

            <div class="col s12 m3">
              <div class="icon-block">
                <h2 class="center indigo-text text-lighten-4"><i class="material-icons large">library_books</i></h2>
                <h5 class="center grey-text text-darken-2">Getting success in your business</h5>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="watch-tutorial-title">
      <div class="section">
      <div class="row">
        <h4>Watch tutorial for better understanding how it works:</h4>
      </div>
      </div>
    </div>

    <div>
      <div class="section">
        <div class="row">
          <video controls class="col offset-s2 s8">
            <source src="video/small.mp4" type="video/mp4">
          </video>
        </div>
      </div>
    </div>

    <footer class="page-footer red darken-1">
        <div class="container">
          <div class="row">
            <div class="col s12">
              <h6 class="white-text">Follow Us:</h6>
              <div class="col offset-s3 s6">
                <img class="social" src="img/social/facebook.png">
                <img class="social" src="img/social/google-plus.png">
                <img class="social" src="img/social/twitter.png">
                <img class="social" src="img/social/vk.png">
              </div>
            </div>
          </div>
        </div>
        <div class="footer-copyright">
          <div class="container">
          Copyright &copy 2015 <a class="orange-text text-lighten-3" href="http://materializecss.com">LovelySurvey</a>
          </div>
        </div>
    </footer>
</body>
</html>